# Generated by Django 2.1.3 on 2019-04-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('email_msg', models.TextField()),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('sender_email', models.EmailField(max_length=254, unique=True)),
                ('reciever_email', models.EmailField(max_length=254, unique=True)),
                ('sender_status', models.CharField(choices=[('s', 'Sent'), ('d', 'Draft')], default='s', max_length=1)),
                ('reciever_status', models.CharField(choices=[('u', 'Unread'), ('r', 'Read')], default='u', max_length=1)),
                ('parent_msg_id', models.IntegerField(default=0)),
            ],
        ),
    ]
